[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
png = "0.17"
radix_fmt = "1.0.0"
rand = "0.8"
rayon = "1.2"
tracing = "0.1"
